### ISSUE TITLE
Fahrenheit for config?

### ISSUE THREAD

**Issue by setherroni** [AlexanderBabel/homebridge-broadlink-rm#1]
Really happy with this plugin, although a bit unsatisfied with my air conditioner config. Currently you can only configure air conditioners using Celsius and my air conditioner uses Fahrenheit. This creates a really weird situation where setting the temperature does a conversion and I can't set it to certain temperatures. I would really appreciate the ability to add temperatures in config as Fahrenheit! Thanks

**Comment by AlexanderBabel** [comment]
I'm sorry, I only working on the tv device type.
