### ISSUE TITLE
No 'exit' button in remote

### ISSUE THREAD

**Issue by lint2015** [AlexanderBabel/homebridge-broadlink-rm#15]
Hi,

Firstly, thank you very much for implementing (multiple!) TV support. I'm in the process of moving over a couple devices to the TV accessory type. Way better than having dozens of on/off switches in the Home app!

Anyway, I noticed in the sample json config there's an "exit" remote button that doesn't show up in the actual remote. Is there something I've don't wrong or is the exit button not currently supported in this plugin? Looking at hands-on articles online, it seems to be a button that some officially supported HomeKit TVs have while some don't.

<img width="249" alt="Screen Shot 2019-05-11 at 1 44 17 pm" src="https://user-images.githubusercontent.com/39164595/57564671-eb642700-73f2-11e9-97ed-439a5f26d608.png">

Also a little confused by what the "powerMode" is or does. I don't see anything related to it in the Home app or the remote. Thanks!

**Comment by AlexanderBabel** [comment]
The exit button was available in the first betas of iOS 12.2. Maybe there are some restrictions or other circumstances why this has been changed.

Anyway the API of homebridge supports this option but I can not influence the iOS behaviour in this point.

Power Mode is used to show the settings page of your television through a button in the settings section of the HomeKit accessory. I don't know why they have chosen this name for this type of action.

**Comment by lint2015** [comment]
Thanks for the explainer. Rather confusing way for Apple to go about things, particularly the Power Mode.

Checked out some of the code and it seems there are more remote buttons that Apple hasn't implemented yet, hopefully that'll come in the future.
