### ISSUE TITLE
How to add Inputs 

### ISSUE THREAD

**Issue by bikinibombe** [AlexanderBabel/homebridge-broadlink-rm#17]
This Plugin is working nicely for me so far but i dont get the Inputs to work properly.
I have a Samsung Smart Tv, to change the Inputs i have to press the Source Button, then swipe right a few times and then press ok. Is there a way to simplify? 

I want to add hdmi 1-3 but i dont get it to work. One Input is working so far, the Netflix Application.

Someone with the same problem?
Here is my config 
       {
            "platform": "BroadlinkRM",
            "name": "Broadlink",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Learnbutton",
                    "type": "learn-code",
                    "host": "192.168.2.121",
                    "enableAutoOff": true,
                    "onDuration": 60,
                    "scanFrequency": true,
                    "isRFSupported": true
                },
                {
                    "name": "Fernseher",
                    "type": "tv",
                    "data": {
                        "off": "26008c009595113813371238121312131114121312131139113813371213121312131114121311141139111411141114111312131213133713121238123812381138133712381200060495951237123813371213121311141213121312381237133712131213121312131213111412381213121312131114121311131238131213371238113912381237123812000d05000000000000000000000000",
                        "on": "26008c009495123811391238111312131213121313121238123812381213121311141114111411141138131212131312121312131213123812131238123713371337123812381100060594951238113912381114121213121213121312381238123811141114111411141114111411381312121312131312121312131238111412381238123713371238123812000d05000000000000000000000000",
                        "remote": {
                            "select": "26008c009395133712381139121213121213121312131139113813371213121311141114111412121213121312381114113911381213123812381138121312381114111411381300060394951238113911381213121312131114111411381337123811141114111312131312121312131114113911131238123812131138123812381114113812131213123812000d05000000000000000000000000",
                            "arrowUp": "2600180194951238113813371213121311141213111411381337123811141114111312131213121312131213111412131138133712131238113812381238113911131213123812000604949512381138123812131114111411141213113812381139111411131213121312131213111411141114111411381238111411391138123811391138121312131238110006059495123812381138121312131114111411141138123812381114121311141113121312131213121312131114113812381213113911391138123812381114111312381200060593951337123812381212121312131312121311391237123812131213111411141213111412121213121312131238113812131238123812381138123811141114123713000d05",
                            "arrowDown": "2600180194931438133614361213121311141114111411381436123811141114111312131411123811141114111411131238123812131114113812381238113812131213143611000605949512381138123812131114111411141113123812381139111312131213121312131337111411131213121312381139111411131238123712391138121312131139110006059495113812381238111411141114131112131238113911381213121313121213111411391113121312131213123811381213141112381139113812381213111411391100060594951138123812381114111411141113121312381238113812131213121312131114113911131213121312131238113911131213123812381138123813121213113911000d05",
                            "arrowLeft": "26008c009495113814361238121311141113121312131238113911381213121312131114131211381213123812131114113911381213121311391114113812381213111411391100060594921537123811391114111312131213121312381138123812131213111411141114113812131238121311141138123812131114113812131238123811141114113812000d05000000000000000000000000",
                            "arrowRight": "26008c009495123811391138121312131114111411141138123812381114111411131213121312131238111411141113123812381114113812131238123811381213121312381100060594951139123713371114111411141114111313371238123811141113121312131213121311391114111312131337113911141138131212381139123712131213123811000d05000000000000000000000000",
                            "back": "2600460094951139113812381213111411141114111312381238113911131213121312131213111411141114113813371213113911141138123811391113131212381213113911000d050000",
                            "exit": "2600460094941238113911381213121312131114111411381337123811141114111312131213123811141237123812131238111412131113123812131114113911141138123812000d050000",
                            "playPause": "26008c009594123713371238111412131212121313121238123811381213121312131114111412371337123811141114121212381213121311141213113813371238111411381200060495941238123713371213111411141213121312371238123812131113131213121312123812381138131212131114113911131213121313121238113911381213123812000d05000000000000000000000000",
                            "info": "2600460093951337123811391113121312131213121311391138123812131114111411141114113812381139123712381213111411141114111411131213121312381139113813000d050000"
                        },
                        "powerMode": {
                            "show": "HEX..."
                        },
                        "volume": {
                            "up": "2600460094941337123812371213121312131213111411391138123812131114121311131213123812381237131212131213111412131114121312121238123811391237123812000d050000",
                            "down": "2600460093951337113912371213121312131213121311391237123812131213111411131213123812381114113813121213121311141213111412371213123812381237133711000d050000"
                        },
                        "inputs": [
                            {
                                "name": "Netflix",
                                "type": "application",
                                "data": [
                                    {
                                        "data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
                                        "pause": 0.3
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {

**Comment by daddvok** [comment]
+1

**Comment by daddvok** [comment]
`"inputs": [
                            {
                                "name": "HDMI 1",
                                "type": "hdmi",
                                "data": "26008C009193133713371435141113121312141113121336133713371312131113121411141113361411141114111411141114111311141114361435143614361435143614361400060295931337133613371312131213121311131212381337113812131213121312131113123812131213121311131213121312131213123712381238123712381238123712000D05000000000000000000000000"
                            },
                            {
                                "name": "TV",
                                "type": "hdmi",
                                "data": [
                                    {
                                        "data": "26008C009193133713371435141113121312141113121336133713371312131113121411141113361411141114111411141114111311141114361435143614361435143614361400060295931337133613371312131213121311131212381337113812131213121312131113123812131213121311131213121312131213123712381238123712381238123712000D05000000000000000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "26008C009193133713371435141113121312141113121336133713371312131113121411141113361411141114111411141114111311141114361435143614361435143614361400060295931337133613371312131213121311131212381337113812131213121312131113123812131213121311131213121312131213123712381238123712381238123712000D05000000000000000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "26008C009193133713371435141113121312141113121336133713371312131113121411141113361411141114111411141114111311141114361435143614361435143614361400060295931337133613371312131213121311131212381337113812131213121312131113123812131213121311131213121312131213123712381238123712381238123712000D05000000000000000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "26002800070B300D13050AB50C820F8E091C0A4106870E380B210A4008170E1B074908840C0009090A000D05",
                                        "pause": 0.3
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    ]
}`

That's work fine
![изображение](https://user-images.githubusercontent.com/47695947/57657005-b0c0e100-75e2-11e9-93e4-ef249d0ffded.png)

**Comment by bikinibombe** [comment]
I dont get it to work :D
Could you help me paste this in my config ?

Here is my full config for Homebridge
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "MagicHome-Platform",
            "debug": true,
            "lights": [
                {
                    "name": "Kitchen LED Strip",
                    "ip": "192.168.2.103",
                    "setup": "RGBW",
                    "purewhite": false,
                    "timeout": 10000
                }
            ]
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Learnbutton",
                    "type": "learn-code",
                    "host": "192.168.2.121",
                    "enableAutoOff": true,
                    "onDuration": 60,
                    "scanFrequency": true,
                    "isRFSupported": true
                },
                {
                    "name": "Garage Door",
                    "type": "garage-door-opener",
                    "openCloseDuration": 8,
                    "data": {
                        "open": "2600500000012...",
                        "close": "2600500000012...",
                        "lock": "2600500000012...",
                        "unlock": "2600500000012..."
                    }
                },
                {
                    "name": "Blind",
                    "type": "window-covering",
                    "totalDurationOpen": 45,
                    "totalDurationClose": 40,
                    "data": {
                        "open": "2600500000012...",
                        "close": "2600500000012...",
                        "stop": "2600500000012..."
                    }
                },
                {
                    "name": "Air Conditioner Advanced",
                    "type": "air-conditioner",
                    "autoCoolTemperature": 23,
                    "autoHeatTemperature": 14,
                    "autoSwitch": "A/C Auto Switch",
                    "data": {
                        "off": "2600500000012...",
                        "temperature30": {
                            "pseudo-mode": "heat",
                            "data": "2600500000012..."
                        },
                        "temperature16": {
                            "pseudo-mode": "cool",
                            "data": "2600500000012..."
                        }
                    }
                },
                {
                    "name": "Fernseher",
                    "type": "tv",
                    "data": {
                        "off": "26008c009595113813371238121312131114121312131139113813371213121312131114121311141139111411141114111312131213133713121238123812381138133712381200060495951237123813371213121311141213121312381237133712131213121312131213111412381213121312131114121311131238131213371238113912381237123812000d05000000000000000000000000",
                        "on": "26008c009495123811391238111312131213121313121238123812381213121311141114111411141138131212131312121312131213123812131238123713371337123812381100060594951238113912381114121213121213121312381238123811141114111411141114111411381312121312131312121312131238111412381238123713371238123812000d05000000000000000000000000",
                        "remote": {
                            "select": "26008c009395133712381139121213121213121312131139113813371213121311141114111412121213121312381114113911381213123812381138121312381114111411381300060394951238113911381213121312131114111411381337123811141114111312131312121312131114113911131238123812131138123812381114113812131213123812000d05000000000000000000000000",
                            "arrowUp": "2600180194951238113813371213121311141213111411381337123811141114111312131213121312131213111412131138133712131238113812381238113911131213123812000604949512381138123812131114111411141213113812381139111411131213121312131213111411141114111411381238111411391138123811391138121312131238110006059495123812381138121312131114111411141138123812381114121311141113121312131213121312131114113812381213113911391138123812381114111312381200060593951337123812381212121312131312121311391237123812131213111411141213111412121213121312131238113812131238123812381138123811141114123713000d05",
                            "arrowDown": "2600180194931438133614361213121311141114111411381436123811141114111312131411123811141114111411131238123812131114113812381238113812131213143611000605949512381138123812131114111411141113123812381139111312131213121312131337111411131213121312381139111411131238123712391138121312131139110006059495113812381238111411141114131112131238113911381213121313121213111411391113121312131213123811381213141112381139113812381213111411391100060594951138123812381114111411141113121312381238113812131213121312131114113911131213121312131238113911131213123812381138123813121213113911000d05",
                            "arrowLeft": "26008c009495113814361238121311141113121312131238113911381213121312131114131211381213123812131114113911381213121311391114113812381213111411391100060594921537123811391114111312131213121312381138123812131213111411141114113812131238121311141138123812131114113812131238123811141114113812000d05000000000000000000000000",
                            "arrowRight": "26008c009495123811391138121312131114111411141138123812381114111411131213121312131238111411141113123812381114113812131238123811381213121312381100060594951139123713371114111411141114111313371238123811141113121312131213121311391114111312131337113911141138131212381139123712131213123811000d05000000000000000000000000",
                            "back": "2600460094951139113812381213111411141114111312381238113911131213121312131213111411141114113813371213113911141138123811391113131212381213113911000d050000",
                            "exit": "2600460094941238113911381213121312131114111411381337123811141114111312131213123811141237123812131238111412131113123812131114113911141138123812000d050000",
                            "playPause": "26008c009594123713371238111412131212121313121238123811381213121312131114111412371337123811141114121212381213121311141213113813371238111411381200060495941238123713371213111411141213121312371238123812131113131213121312123812381138131212131114113911131213121313121238113911381213123812000d05000000000000000000000000",
                            "info": "2600460093951337123811391113121312131213121311391138123812131114111411141114113812381139123712381213111411141114111411131213121312381139113813000d050000"
                        },
                        "powerMode": {
                            "show": "HEX..."
                        },
                        "volume": {
                            "up": "2600460094941337123812371213121312131213111411391138123812131114121311131213123812381237131212131213111412131114121312121238123811391237123812000d050000",
                            "down": "2600460093951337113912371213121312131213121311391237123812131213111411131213123812381114113813121213121311141213111412371213123812381237133711000d050000"
                        },
                        "inputs": [
                            {
                                "name": "Netflix",
                                "type": "application",
                                "data": [
                                    {
                                        "data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
                                        "pause": 0.3
                                    },
                                    {
                                        "data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
                                        "pause": 0.3
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "platform": "Hue",
            "host": "",
            "users": {
                "001788FFFE70C53B": "z17kkIjzWTl5UIcNpK9D5w7lNIXMk8jm5iDxtsJ2"
            },
            "nativeHomeKit": true,
            "sensors": false,
            "nativeHomeKitSensors": true,
            "excludeSensorTypes": [],
            "lowBattery": 25,
            "lights": false,
            "nativeHomeKitLights": true,
            "wallSwitch": true,
            "groups": false,
            "group0": false,
            "rooms": false,
            "schedules": false,
            "rules": false,
            "heartrate": 5,
            "timeout": 5,
            "resource": true,
            "parallelRequests": 10,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20
        }
    ],
    "accessories": [
        {
            "accessory": "Synology",
            "name": "DS3615XS",
            "ip": "192.168.2.",
            "mac": "70:85:c2:02:29:50",
            "port": "5000",
            "secure": false,
            "account": "",
            "password": "",
            "version": 6,
            "timeout": 5000,
            "doPolling": true,
            "pollingInterval": 60
        },
        {
            "name": "AirRohr",
            "accessory": "airrohr",
            "json_data": "",
            "public_temperature_json_data": "http://api.luftdaten.info/v1/sensor/7016/",
            "public_airquality_json_data": "http://api.luftdaten.info/v1/sensor/3323/",
            "sensor_id": "2342523",
            "update_interval_seconds": 60,
            "history": {
                "storage": "fs"
            }
        }
    ]
}

**Comment by kiwi-cam** [comment]
@bikinibombe You might have more luck getting support from one of the homebridge communities instead of raising an issue e.g. https://www.reddit.com/r/homebridge/. 

It's much quicker to get a response from the community than it is from the Dev.

EDIT: Also, it looks like you've got some passwords in your config above. You might want to change these now.

**Comment by bikinibombe** [comment]
So i think i got a real Issue now. Yesterday i tried to change the config to add my Hdmi Inputs long story short, i got it to work i mean the json config but now my Homebridge wont start up. 
I tried the command for the log and there stands: The Type Hdmi is not supported for homebridge broadlink. 
As soon as i changed my Input „Netflix“ from application to hdmi it worked but not the Inputs below in my config.
Ill put the updated config in here.

`{
					"name": "Fernseher",
					"type": "tv",
					"pingIPAddress": "192.168.2.108",
                    "pingFrequency": 120,
                    "pingIPAddressStateOnly": true,
					"data": {
						"off": "26008c009595113813371238121312131114121312131139113813371213121312131114121311141139111411141114111312131213133713121238123812381138133712381200060495951237123813371213121311141213121312381237133712131213121312131213111412381213121312131114121311131238131213371238113912381237123812000d05000000000000000000000000",
						"on": "26008c009495123811391238111312131213121313121238123812381213121311141114111411141138131212131312121312131213123812131238123713371337123812381100060594951238113912381114121213121213121312381238123811141114111411141114111411381312121312131312121312131238111412381238123713371238123812000d05000000000000000000000000",
						"remote": {
							"select": "26008c009395133712381139121213121213121312131139113813371213121311141114111412121213121312381114113911381213123812381138121312381114111411381300060394951238113911381213121312131114111411381337123811141114111312131312121312131114113911131238123812131138123812381114113812131213123812000d05000000000000000000000000",
							"arrowUp": "2600180194951238113813371213121311141213111411381337123811141114111312131213121312131213111412131138133712131238113812381238113911131213123812000604949512381138123812131114111411141213113812381139111411131213121312131213111411141114111411381238111411391138123811391138121312131238110006059495123812381138121312131114111411141138123812381114121311141113121312131213121312131114113812381213113911391138123812381114111312381200060593951337123812381212121312131312121311391237123812131213111411141213111412121213121312131238113812131238123812381138123811141114123713000d05",
							"arrowDown": "2600180194931438133614361213121311141114111411381436123811141114111312131411123811141114111411131238123812131114113812381238113812131213143611000605949512381138123812131114111411141113123812381139111312131213121312131337111411131213121312381139111411131238123712391138121312131139110006059495113812381238111411141114131112131238113911381213121313121213111411391113121312131213123811381213141112381139113812381213111411391100060594951138123812381114111411141113121312381238113812131213121312131114113911131213121312131238113911131213123812381138123813121213113911000d05",
							"arrowLeft": "26008c009495113814361238121311141113121312131238113911381213121312131114131211381213123812131114113911381213121311391114113812381213111411391100060594921537123811391114111312131213121312381138123812131213111411141114113812131238121311141138123812131114113812131238123811141114113812000d05000000000000000000000000",
							"arrowRight": "26008c009495123811391138121312131114111411141138123812381114111411131213121312131238111411141113123812381114113812131238123811381213121312381100060594951139123713371114111411141114111313371238123811141113121312131213121311391114111312131337113911141138131212381139123712131213123811000d05000000000000000000000000",
							"back": "2600460094951139113812381213111411141114111312381238113911131213121312131213111411141114113813371213113911141138123811391113131212381213113911000d050000",
							"exit": "2600460094941238113911381213121312131114111411381337123811141114111312131213123811141237123812131238111412131113123812131114113911141138123812000d050000",
							"playPause": "26008c009594123713371238111412131212121313121238123811381213121312131114111412371337123811141114121212381213121311141213113813371238111411381200060495941238123713371213111411141213121312371238123812131113131213121312123812381138131212131114113911131213121313121238113911381213123812000d05000000000000000000000000",
							"info": "2600460093951337123811391113121312131213121311391138123812131114111411141114113812381139123712381213111411141114111411131213121312381139113813000d050000"
						},
						"powerMode": {
							"show": "HEX..."
						},
						"volume": {
							"up": "2600460094941337123812371213121312131213111411391138123812131114121311131213123812381237131212131213111412131114121312121238123811391237123812000d050000",
							"down": "2600460093951337113912371213121312131213121311391237123812131213111411131213123812381114113813121213121311141213111412371213123812381237133711000d050000"
						},
						"inputs": [{
							"name": "HDMI 1",
							"type": "hdmi",
							"data": [{
									"data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
									"pause": 0.3
								},
								{
									"data": "26008c009594123713371238111411141212121313121238113911381213121311141213111411381312121312381238113813371213121311381238121312131213111412371200060594951237133712381114111312131213121311391237133712131213121312131113123812131213113911381238123811141114123713371213111412131114123712000d05000000000000000000000000",
									"pause": 0.3
								}
							]
						}]
					}
				},
				{
					"inputs": [{
						"name": "HDMI",
						"type": "hdmi",
						"data": [{
								"data": "2600500000012...",
								"pause": 0.3
							},
							{
								"data": "2600500000012...",
								"pause": 0.3
							},
							{
								"data": "2600500000012...",
								"pause": 0.3
							},
							{
								"data": "2600500000012...",
								"pause": 0.3
							}
						]
					}]
				}
			]
		},
		{
			"inputs": [{
				"name": "HDMI",
				"type": "hdmi",
				"data": [{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					}
				]
			}]
		},
		{
			"inputs": [{
				"name": "HDMI",
				"type": "hdmi",
				"data": [{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					},
					{
						"data": "2600500000012...",
						"pause": 0.3
					}
				]
			}]
		}`

**Comment by bikinibombe** [comment]
Anyone an Idea ?

**Comment by kiwi-cam** [comment]
The config you've supplied doesn't parse on https://jsonlint.com/. I'd suggest checking you've got your brackets lined up correctly.  Also, is there anything in the logs - a parsing error would generally show up there?
EDIT Looks like you've defined "inputs" multiple times - there should only be one for each TV.

**Comment by AlexanderBabel** [comment]
As @kiwi-cam said, please create a new post in the subreddit instead.
