### ISSUE TITLE
Channel numbers and inputs

### ISSUE THREAD

**Issue by ghost** [AlexanderBabel/homebridge-broadlink-rm#19]
Hello,

First of all, I really want to thank you for adding TV support to this plugin.
I have two questions though.

1. Is it possible to add numbers (1, 2, etc.) or Channel_Up/Down  to switch channels?
2. Whatever I do and how many times I check the issues, I can't make the Inputs work. I add three inputs, one for the local TV source, one for the Apple TV and one for the Xbox. Only two of them appear in the list on device and it does not do anything.

Would you please help me?

**Comment by gr8gtp** [comment]
Here is how my inputs config look, all 4 work and show up. I did have an issue where only two showed up I added an enter after one of them resaved and restarted homebridge. Killer app on phone and it showed up. Hope it helps

"inputs": [
                            {
                                "name": "SLEEP",
                                "type": "hdmi",
                                "data": "260090000a460a450a450c1d0a1f091f0a45091f0a450a450a460b1d0a460a1e0b1d0a1f0900030e0b450a450b4409200b1d0b1e09460a1e0b450a450a460a1e09460b1e0a1e0a1e0b00030d0b440c440a450b1d0b1e091f0a450a1f0a450b450a450b1d0a4509200a1e0b1d0b00030d0b440a460b450a1e091f0a1e0a460a1e0a450b440b450b1e0a450b1d0a1f091f09000d050000000000000000"
                            },
                            {
                                "name": "DIRECTV",
                                "type": "hdmi",
                                "data": "2600900009460b450b440a1f091f0a1e0a46091f0a450a1f091f091f094609470b440b1e0a00030d0b4509440d450a1e0a1e0a1e0a46091f09470a1e091f0a1e0a460a450b45091f0a00030e0c410e4408470a1e08200a1f09460a1e0a450c1d0b1d0b1e09460b450b440b1d0a00030d0c440b450b440b1e091f0a1e0a450a1f09460b1d0b1e091f0b440c4409460a1e0a000d050000000000000000"
                            },
                            {
                                "name": "SWITCH",
                                "type": "hdmi",
                                "data": "260090000b450a450a460a1e091f0b1d0b45091f09460a1f091f0a450a4609460b450a1d090002e90b430a460b450b1d0a1e0a1f0a450b1d0a4509200b1d0b4509460b450a440a1f0a0002e60b4509470a450b1d0a1f091f0a450a1f0a45091f0a1f0a450a4609460b440b1e0a0002e50b460b430a470a1e091f0a1e0a46091f0b440920091f0b450b43094709470a1e0b000d050000000000000000"
                            },
                            {
                                "name": "DENON",
                                "type": "hdmi",
                                "data": "260090000a450b450a450a1e0b1e0c1c0b440b1e0a450b1d0b1d0b450c430b1e09460c1c0a00030e0b450b440b440b1e0a1e0b1d0a4608200b440b1f081f0a450c4411160c440c1d0a00030d0b440c440a460a1e0b1d0c1c0c44091f0b450a1e0a1e0b450a450b1d0a460b1d0b00030d09450c450a450d1b0b1e091f0b440c1c0b450c1c0c1c0b450b420c1f09460b1d0a000d050000000000000000"
                            }
]
