### ISSUE TITLE
Can’t add type=‘tv’ devices 

### ISSUE THREAD

**Issue by jorgeserna** [AlexanderBabel/homebridge-broadlink-rm#2]
if I configure a type: "tv" device I get this error:

AssertionError [ERR_ASSERTION]: ServiceManager requires the "type" to be provided.
at new ServiceManager (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/serviceManager.js:7:5)
at TVAccessory.setupServiceManager (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/tv.js:150:27)

Devices with type "switch" work without problems. Any idea what may be happening? Because type is clearly defined. In fact, if I simply change my config.json and replace "tv" with "switch", now homebridge starts without problem, and simply lists the device as a switch.

Thanks!!

**Comment by AlexanderBabel** [comment]
Are you sure you have my version installed? If not use `npm i -g --unsafe-perm git+https://github.com/AlexanderBabel/homebridge-broadlink-rm.git`

**Comment by jorgeserna** [comment]
Yes, the stack trace is in tv.js that is from your version. I installed it with npm i -g git+https://github.com/AlexanderBabel/homebridge-broadlink-rm.git --unsafe-perm

**Comment by AlexanderBabel** [comment]
Can you please post your config? Thanks.

**Comment by jorgeserna** [comment]
{
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
{
"name":"TV3",
"type":"switch",
"data": {
"off": "0000 006D 0000 0022 00AC 00AC 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0689",
"on": "0000 006D 0000 0022 00AC 00AC 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0689",
"remote": {
"select": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"arrowUp": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"arrowDown": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"arrowLeft": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"arrowRight": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"back": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"exit": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"playPause": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"info": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000"
},
"powerMode": {
"show": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000"
},
"volume": {
"up": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
"down": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000"
},
"inputs": [
{
"name": "INPUT 1",
"type": "hdmi",
"data": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000"
}
]
}
},
        {
          "name":"TeleVolUp",
          "type":"switch",
	  "enableAutoOff":true,
	  "onDuration":1,
          "data":{
					"on": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000",
					"off": "26008c00949412371337131215101411121313371213123713371312131212381213123712131337123814111411113815351411121312131213143515351312131211391238130005e192961237133713121214111312131337121312371535121412121238131113371312133713371213131113371535121314111213131213361634131212131337123713000d05000000000000000000000000"
          }
        },

        {
          "name":"TeleVolDwn",
          "type":"switch",
	  "enableAutoOff":true,
	  "onDuration":1,
          "data":{
					"on": "2600460095931238133615111212131212131337141112371436141113121238121312371510133712381213113912371436141113121411121312371312131213131435123814000d050000",
					"off": "2600460095931238133615111212131212131337141112371436141113121238121312371510133712381213113912371436141113121411121312371312131213131435123814000d050000"
          }
        }
      ]
    }

**Comment by jorgeserna** [comment]
This one works, but if I change “switch” to “tv” in TV3 it breaks

**Comment by jorgeserna** [comment]
This is the full stack trace :

[2019-3-5 21:29:55] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
assert.js:49
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: ServiceManager requires the "type" to be provided.
    at new ServiceManager (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/serviceManager.js:7:5)
    at TVAccessory.setupServiceManager (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/tv.js:150:27)
    at new HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:36:10)
    at new BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new TVAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/tv.js:9:5)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:66:32)
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:61:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:367:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:311:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by jorgeserna** [comment]
Ok, found the issue. My base home bridge install was not properly updated. Fixed that now and it’s working. Thank you very much!!
