### ISSUE TITLE
Second television has disappeared

### ISSUE THREAD

**Issue by djrams10** [AlexanderBabel/homebridge-broadlink-rm#20]
hello, I had to add both tvs all worked well until the second disappears two days ago. I did not do anything. I happen to see tele in the homebridge terminal but it does not appear in homekit. however, there is no error. i tried deleting the line in config.json to reboot and put it back but the tv icon does not come back. you have an idea? thank you.

**Comment by djrams10** [comment]
when I put the second tv type "switch" it comes back. and I put in type "tv" it disappears. Do you have an idea? thanks

**Comment by bkarakashev** [comment]
I am having the same issue :(

**Comment by djrams10** [comment]
it is reappropriated alone from my side
