### ISSUE TITLE
Loading the plugging error 

### ISSUE THREAD

**Issue by bkarakashev** [AlexanderBabel/homebridge-broadlink-rm#24]
Hello,
I've just installed this plugin and restarted Homebridge.
And then straight away I start seeing this error:

`Loaded plugin: homebridge-broadlink-rm-tv
/usr/local/lib/node_modules/homebridge/lib/api.js:150
    throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
Stopped Homebridge.`

Can you please put some documentatuon on how to use the TV add-on.
And anybody else had this error?

Thanks

**Comment by AlexanderBabel** [comment]
It looks like you have the old Homebridge-broadlink-rm plugin also installed.

If your issue still exists feel free to open this issue again!
