### ISSUE TITLE
All possible buttons?

### ISSUE THREAD

**Issue by radiocolin** [AlexanderBabel/homebridge-broadlink-rm#25]
Is the sample config.json feature-complete in terms of available buttons? Or are there more buttons that can be configured?

**Comment by kiwi-cam** [comment]
Hi @radiocolin If you still have this question... are you referring to the TV "remote" buttons? I've just refreshed the README, from the code. [This](https://github.com/AlexanderBabel/homebridge-broadlink-rm/blob/master/README.md#remote-key-value-object) has all the supported remote buttons.
