### ISSUE TITLE
Add multiple pseudo modes for Air conditioner temperature

### ISSUE THREAD

**Issue by Cloudore** [AlexanderBabel/homebridge-broadlink-rm#29]
Hey @AlexanderBabel ,

Thank you for continuing support to this plug in,

If you are willing, it'd be great to add support to the air-conditioner-pro accessory to this version as well, it allows to adjust the AC per temperature AND mode in the json so that the correct corresponding signal will be sent each time. This was developed by a someone on GitHub who deleted it and I had a clone so re-uploaded it here

https://github.com/Cloudore/homebridge-broadlink-rm

Here is how it looks in my config.json

https://github.com/Cloudore/Myhbridge/blob/master/config.json

I would love to do it myself but I can barely handle python, don't have the knowledge to merge both versions without messing something up.

Have a good one

**Comment by kiwi-cam** [comment]
Thanks for providing the source @Cloudore . I thought I'd take a look at comparing the two versions too but they were so different it wasn't realistic. Instead you provided motivation to take a go at building it into @AlexanderBabel 's fork myself, which I did today.  I have a fork with a couple of tweaks which I've now added this to.  If you'd like to try my fork you can install it using:
`npm i -g git+https://github.com/kiwi-cam/homebridge-broadlinkrm-acfile`

The Repo is [here ](https://github.com/kiwi-cam/homebridge-broadlinkrm-acfile) if you'd like to take a look. The documentation is basically just the README.md and everyone else's.

EDIT - and by all means @AlexanderBabel feel free to merge, copy, and/or build on my work.

**Comment by AlexanderBabel** [comment]
@kiwi-cam Thank you for your work! You can create a pull request if you want and I would take a look at your changes and add them to this fork.

**Comment by kiwi-cam** [comment]
> @kiwi-cam Thank you for your work! You can create a pull request if you want and I would take a look at your changes and add them to this fork.

Kinda new to Github.... I think I've just done that.

**Comment by Cloudore** [comment]
@kiwi-cam That's awesome, thank you so much!

**Comment by AlexanderBabel** [comment]
@kiwi-cam Your pull request has been merged now. Please check if everything still works as expected. Thank you guys for your effort and time!

**Comment by kiwi-cam** [comment]
Thanks @AlexanderBabel . Great to see this package getting some more love.

I've just updated mine and so far everything looks great.  I am second guessing my logic on one point though. My AC hex codes include all the configuration (mode, temperature, fan speed... everything). It looks like if the mode and temperature are changed together the mode hex code doesn't get sent, only the temperature one. This works fine for me, but may not work for others.  Is anyone (@Cloudore ) able to confirm this?

**Comment by kiwi-cam** [comment]
Actually... it looks like even @lprhodes's fork only sends the temperature hex... the heat and cool codes don't appear to get used. I set mine to "F00D474C001" (Foo Data Cool in 1337) so I could see it clearly in the logs... nothing.

So this "bug" I might've found, but can't really test, appears to have always existed ¯\_(ツ)_/¯

**Comment by Cloudore** [comment]
@kiwi-cam My split unit's hex code provides all on screen settings as well on a single hex code!
