### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by setherroni** [AlexanderBabel/homebridge-broadlink-rm#3]
I currently have the original homebridge-broadlink-rm plugin from iprhodes. I'm pretty new to these commands so I'm not sure how to get the tv plugin in here. I tried doing `npm i git+https://github.com/AlexanderBabel/homebridge-broadlink-rm.git` but I just get this error:

![image](https://user-images.githubusercontent.com/8891355/53996323-d0242500-40ec-11e9-8f9d-bda5b2074b9e.png)

**Comment by AlexanderBabel** [comment]
looks like a git error. Just google it and you'll find something.
