### ISSUE TITLE
Inputs Losing Name

### ISSUE THREAD

**Issue by mitch7391** [AlexanderBabel/homebridge-broadlink-rm#32]
Hi, love your work here :) one small thing I have noticed is Input 2 and Input 3 always lose their name that I have defined in my config. This requires me to change it in the setup of the accessory in HomeKit and then it loses it again after a while. Any ideas why this might be happening?

![01260523-BE43-4AD3-B066-0ED766E0EDD1](https://user-images.githubusercontent.com/40288237/65480979-3bd1b200-dec6-11e9-91c4-66d1ec2bb74d.png)

**Comment by kiwi-cam** [comment]
Have you defined a name for them in your config.json?
```
"inputs": [
  {
    "name": "INPUT 1",
    "type": "hdmi",
    "data": "HEX..."
  }
]
```

**Comment by mitch7391** [comment]
Thanks @kiwi-cam, silly mistake it looks like for those two inputs I had accidentally put in “input” instead of “name”. I should have noticed that myself! :)
