### ISSUE TITLE
Is possible to control RF thermostats with RM Pro?

### ISSUE THREAD

**Issue by Olepir** [AlexanderBabel/homebridge-broadlink-rm#39]
Is possible to control RF thermostats and read temperature with RM Pro?
Thanks

**Comment by kiwi-cam** [comment]
Absolutely. If you don’t specify a file, w1 device, or mqtt the RM device will be used.

**Comment by Olepir** [comment]
> Absolutely. If you don’t specify a file, w1 device, or mqtt the RM device will be used.

Can you explain more – what you meant by “specify a file, w1 device, or mqtt”?
Thanks!

**Comment by kiwi-cam** [comment]
Just don't include w1DeviceID, temperatureFilePath, or mqttURL in your config.json file. It'll fall back to trying the Broadlink device to read the temperature if they're missing.

**Comment by Olepir** [comment]
> Just don't include w1DeviceID, temperatureFilePath, or mqttURL in your config.json file. It'll fall back to trying the Broadlink device to read the temperature if they're missing.

Can you post a sample for settings?

**Comment by kiwi-cam** [comment]
Sure thing. This should work:
```
.....
			"accessories": [{
					"name": "Heat Pump",
					"type": "air-conditioner",
					"defaultCoolTemperature": 21,
					"defaultHeatTemperature": 23,
					"data": {
						"off": "260076006d.......",
						"on": "260006016d......."
....
```

Feel free to post your config.json if you can't get it to work.

**Comment by Olepir** [comment]
"off": "260076006d.......",
"on": "260006016d……."
is these settings for on/off your “Heat Pump”?

**Comment by kiwi-cam** [comment]
> is these settings for on/off your “Heat Pump”?

Haha, no. I truncated it so it was easier to read.

If you'd like, my actual config.json is [here](https://github.com/kiwi-cam/MyHomeBridge/blob/master/var/homebridge/config.json).

**Comment by Olepir** [comment]
Here’s settings for a floor heater that I trying to control with no luck
`{
"platform": "BroadlinkRM",
"name": "Broadlink RM",
"hideScanFrequencyButton": false,
"hideLearnButton": false,
"hideWelcomeMessage": false,
"accessories": [{
"name": "Floor Heater",
"type": "air-conditioner",
"data": {
"temperature22": {
"pseudo-mode": "heat",
"data": "b200ba000..."
},
"temperature18": {
"pseudo-mode": "cool",
"data": "b200ba000..."
}
}
}]
}`

**Comment by kiwi-cam** [comment]
Which part isn't working, the control or reading the temperature?

Also, can you share your logs so we can see what is happening?

**Comment by Olepir** [comment]
0|homebrid | [11/6/2019, 9:30:30 PM] There was a problem reading your config.json file.
0|homebrid | [11/6/2019, 9:30:30 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
0|homebrid | [11/6/2019, 9:30:30 PM] 
0|homebrid | SyntaxError: Unexpected end of JSON input
0|homebrid | at JSON.parse (<anonymous>)
0|homebrid | at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:212:19)
0|homebrid | at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
0|homebrid | at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
0|homebrid | at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebrid | at Module._compile (internal/modules/cjs/loader.js:689:30)
0|homebrid | at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|homebrid | at Module.load (internal/modules/cjs/loader.js:599:32)
0|homebrid | at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|homebrid | at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by kiwi-cam** [comment]
Well the config.json you pasted validates fine on http://jsonlint.com. Are you sure that's the config file it's reading? Does homebridge run with a -U paramter pointing to the directory holding that file?

**Comment by Olepir** [comment]
Yes, that’s the file… ((
