### ISSUE TITLE
"inputs" key-value object - data

### ISSUE THREAD

**Issue by duculete** [AlexanderBabel/homebridge-broadlink-rm#41]
for the inputs object we have 3 keys: name, type, data.

can I use for data key different value than a string?
for example:

 "inputs": [
              {
                "name": "INPUT 1",
                "type": "hdmi",
                "data": [
              {
                "data": "SOURCE_HEX_1...",
                "pause": 0.3
              },
              {
                "data": "DOWN_ARROW_HEX_2...",
                "sendCount": 2,
                "interval": 0.1,
                "pause": 0.3
              }
            ]
              }
            ]

**Comment by kiwi-cam** [comment]
Absolutely. I've seen this used frequently for input selection when there isn't a hexcode for a device. I.e. you can send the hexcode for a known device followed by a sequence of hexcodes to cycle to the desired input.

Are you having issues getting this to work?

**Comment by duculete** [comment]
Hello,

I am out of the country. I will try when I'll be back!

Question: this plugin has the same name as the original (fork) so I need to uninstall homebridge-broadlink-rm (original one) and then install this one. does the old(already configured) accessories will work (the ones I have configured with the original homebridge-broadlink-rm)?

**Comment by duculete** [comment]
Hello,

I confirm it's working with composed data inputs.

**Comment by kiwi-cam** [comment]
Thanks for the update. Glad you got it working.
