### ISSUE TITLE
PickUp temperature on other device

### ISSUE THREAD

**Issue by g0tama** [AlexanderBabel/homebridge-broadlink-rm#42]
Hi

I'm trying to configure this plugin for the air conditionner with RM mini.
The ambient temperature is always the same (14°C) iand n the log I found:
`[10/23/2019, 9:38:15 PM] [Remote Salon] Climatisation addTemperatureCallbackToQueue (requested temperature from device, waiting)`

`[10/23/2019, 9:38:15 PM] [Remote Salon] Climatisation onTemperature (14)`

The question is how and where the plugin take the temperature? I found in the doc the variable `temperatureFilePath`but if I can and how use it.
Do you know any possibility to pick up the ambiant temperature for the air conditionner directly by another device in homekit or homebridge (Broadlink A1 by exemple)?

Thanks

**Comment by kiwi-cam** [comment]
This makes sense. If you don't specify w1device, temperatureFilePath, or mqttURL and mqttTopic then it will attempt to get the temperature from your Broadlink device... the RM Mini doesn't include a thermometer.

Where would you like to read the temperature from? You can read from a text file, connect a w1device (like [this](https://www.amazon.com/Cenrykay-Temperature-Waterproof-Stainless-Measurement/dp/B07H3P8LRT/ref=sr_1_1_sspa?keywords=ds18b20&qid=1571861987&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzSlZKTk0yUVNGWE05JmVuY3J5cHRlZElkPUEwMjU2ODMwMjk2MlZYUkhNWVVPTyZlbmNyeXB0ZWRBZElkPUEwNzI2MDQ2MlA1SjRLR1hKVk44UCZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=)), or an external MQTT device.

**Comment by g0tama** [comment]
That I think. there are any possibilities to directly read the temperature from another Broadlink device like the A1. I will test with MQTT.
Do you know if this plugin launch a local MQTT broker?

Thanks for your help

**Comment by kiwi-cam** [comment]
No - from what I've seen in the code it's just a client.
