### ISSUE TITLE
minTemperature setting

### ISSUE THREAD

**Issue by LordCYCU** [AlexanderBabel/homebridge-broadlink-rm#44]
Hi,

I have a small problem with setting minimal temperature property. My AC has 17 as the lowest setting, but log shows that the lowest number accepted by plugin is 10...

0|homebridge  | AssertionError: [CONFIG ERROR] minTemperature (17) must be <= 10: expected 17 to be below 11

Maybe there is something that I don't know :-)

Config cutout:
 "name": "Air Conditioner Advanced",
                        "type": "air-conditioner",
                        "minTemperature": 10,
                        "maxTemperature": 30,
                        "defaultCoolTemperature": 24,
                        "defaultHeatTemperature": 24,
                        "mqttURL": "mqtt://192.168.0.67",
                        "mqttUsername": "XXXXXX",
                        "mqttPassword": "XXXXXX",
                        "mqttTopic": "tele/sonoff171/SENSOR",
                        "autoSwitch": "A/C Auto Switch",

![log](https://user-images.githubusercontent.com/57416671/68243933-f3a0c600-0013-11ea-9631-4066d4cf00ee.png)

**Comment by kiwi-cam** [comment]
Unfortunately, I don't think we can do much about this. This is the comment made on those checks:
> minTemperature can't be more than 10 or HomeKit throws a fit

If you set the minTemperature to 10 (or omitted this optional value), what's the impact? You could set it to 10 and configure all the hexcodes for 10-18 to be the same. That way HomeKit is happy; people can set the temperature lower than 18 but the result will be the AC cooling to it's minimum anyway.

**Comment by LordCYCU** [comment]
Thanks for response :-)

Impact is You see the dial that can be set to 10, but this is only user experience matter ...
