### ISSUE TITLE
Cannot see volume controls 

### ISSUE THREAD

**Issue by sushenmathur** [AlexanderBabel/homebridge-broadlink-rm#5]
I've added my config and can see TV in homekit but cant see volume controls.
Here is my config file

{
                    "name": "TV",
                    "type": "tv",
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        }
                    }

**Comment by kiwi-cam** [comment]
You don’t see them 😊

When you’re in the remote, via control centre, the volume buttons on the side of your phone control the TV volume.

**Comment by S474N** [comment]
And you can see controls?

You must use ControlCentre with ATV controller and Volume+ and Volume- on side of your iPhone/iPad.

**Comment by sushenmathur** [comment]
Thanks for clarifying, works like a charm..
