### ISSUE TITLE
tv is not shown properly

### ISSUE THREAD

**Issue by liorsu** [AlexanderBabel/homebridge-broadlink-rm#54]
I added a tv type as shown in the example.json in the repository
Added multiple hdmi inputs
on the homekit the icon is shown as a television, but i see nothing except turning the tv on\off and the current input and some weird "Show as separate tiles" option.
Can't see a volume or input selection, is it something wrong that I did or apple changed something?
Running ios 13.2.2

**Comment by kiwi-cam** [comment]
Could you share the section of the config.json that you used?  I sounds like you've got `"type":"switch"` which is still in the example from the original project without tv support. [Jump to here](https://github.com/AlexanderBabel/homebridge-broadlink-rm/blob/master/config-sample.json#L271) for the updated example.

**Comment by kiwi-cam** [comment]
I just re-read your post. Sounds like it's all setup correctly then. The "trick" that is hard to find is that you don't use the remote controls through the Home app, you need to swipe to access Control Centre and open the remote from there. The remote controls then use your device's volume buttons.

**Comment by liorsu** [comment]
I just checked that. I do see my device in the remote app
But I don't see all the configured options, I see navaigation, play\pause, back and info
Where are the input selection, volume and power on\off options?

**Comment by liorsu** [comment]
This is my configuration btw:

{
                    "name": "Receiver",
                    "type": "tv",
                    "host": "34:ea:dr:fa:cd:4a",
                    "data": {
                        "off": "2600cc006d380d0f0d0e0e2a0d0e0e2a0d0e0e2a0d0e0e0e0d2a0e0e0d0f0d2a0e290e0e0d0f0d0f0d0e0e0e0d0f0d0e0e0e0e290e0e0e290e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d0f0d0f0d0e0e0e0d0f0d0e0e2a0d0e0e0e0e0e0d2a0d0f0d0f0d0e0e0009736d380d0e0e0e0d2a0e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0e0e2a0d2a0d0f0d0e0e0e0d0f0d0e0e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d0f0d2a0d0f0d0e0e0e0e290e0e0e0e0d0f0d000d05000000000000000000000000",
                        "on": "2600cc006d380d0f0d0e0e2a0d0e0e2a0d0e0e2a0d0e0e0e0d2a0e0e0d0f0d2a0e290e0e0d0f0d0f0d0e0e0e0d0f0d0e0e0e0e290e0e0e290e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d0f0d0f0d0e0e0e0d0f0d0e0e2a0d0e0e0e0e0e0d2a0d0f0d0f0d0e0e0009736d380d0e0e0e0d2a0e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0e0e2a0d2a0d0f0d0e0e0e0d0f0d0e0e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d0f0d2a0d0f0d0e0e0e0e290e0e0e0e0d0f0d000d05000000000000000000000000",
                        "remote": {
                            "select": "HEX...",
                            "arrowUp": "HEX...",
                            "arrowDown": "HEX...",
                            "arrowLeft": "HEX...",
                            "arrowRight": "HEX...",
                            "back": "HEX...",
                            "exit": "HEX...",
                            "playPause": "HEX...",
                            "info": "HEX..."
                        },
                        "powerMode": {
                            "show": "HEX..."
                        },
                        "volume": {
                            "up": "2600cc006d380d0e0e0e0d2a0e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0e0e2a0d2a0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d2a0e2a0d2a0d0f0d2a0d0f0d0e0e0e0d0f0d2a0d2a0e0e0d2a0e0e0d2a0e0e0d0009736e370e0e0d0f0d2a0d0f0d2a0d0f0d2a0d0f0d0e0e2a0d0e0e0e0d2a0e2a0d0e0e0e0d0f0d0e0e0e0e0e0d0f0d0e0e2a0d0e0e2a0d0e0e0e0d0f0d0e0e0e0e0e0d0f0d2a0d2a0e290e0e0e290e0e0e0e0d0f0d0e0e2a0d2a0d0f0d2a0d0f0d2a0d0e0e000d05000000000000000000000000",
                            "down": "2600cc006e370e0e0e0e0d2a0d0f0d2a0d0f0d2a0d0f0d0e0f290d0e0e0e0e290f290d0e0f0d0e0e0d0f0d0e0e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d2a0e0e0e0e0d0e0e2a0d2a0e290e0e0d2a0f0d0d0f0d0e0f0d0e290e2a0e0d0e0e0e0e0d2a0e0e0d0009736f360e0e0d0f0d2a0d0f0d2a0d0f0d2a0d0f0d0e0e2a0d0e0e0e0e290e2a0d0e0f0d0e0e0d0f0d0e0e0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0d2a0e0e0d0f0d0e0e2a0d2a0d2a0e0e0d2a0e0e0d0f0d0e0e0e0e2a0d2a0d0f0e0d0e0e0d2a0e0e0d000d05000000000000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "Apple TV",
                                "type": "hdmi",
                                "data": "2600cc006d380e0d0e0e0e290e0e0e290e0e0e290f0d0e0e0d2a0e0e0d0f0d2a0d2a0e0e0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e2a0d2a0d0f0d0e0e2a0d0e0e2a0d2a0e0e0d2a0d0f0d0e0e0e0e0e0d2a0e290e2a0d0e0e2a0d0e0e0009736d380d0f0d0e0e2a0d0e0e2a0d0e0e2a0d0e0e0e0d2a0e0e0d0f0d2a0d2a0e0e0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e2a0d2a0d0f0d0f0d2a0d0f0d2a0d2a0d0f0d2a0d0f0d0f0d0e0e0e0d2a0e290e2a0d0e0e2a0e0d0e000d05000000000000000000000000"
                            },
                            {
                                "name": "Xbox",
                                "type": "hdmi",
                                "data": "2600cc006d380e0e0d0e0e2a0d0e0e2a0d0e0e2a0d0e0e0e0e290e0e0d0f0d2a0d2a0e0e0e0e0d0f0d0e0e0e0d0f0d0e0e0e0e290e0e0e290e0e0e0e0d0f0d2a0d0f0d2a0d0f0d2a0d0f0d2a0d2a0e0e0d2a0e0e0d0f0d0e0e0e0d2a0f290d2a0d2a0d0f0d0e0e0009736d380d0e0e0e0e290e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0e0e2a0d2a0d0f0d0e0e0e0e0e0d0f0d0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0e290e0e0e290e0e0e290e0e0e290e2a0d0e0e2a0d0e0e0e0e0e0d0f0d2a0d2a0e290e2a0d0e0e0e0d000d05000000000000000000000000"
                            },
                            {
                                "name": "Tv Audio",
                                "type": "hdmi",
                                "data": "2600cc006d380d0e0e0e0e290e0e0d2a0e0e0e290e0e0e0e0d2a0d0f0d0f0d2a0e290d0f0d0f0d0e0e0e0d0f0d0e0e0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e0e0d2a0e0e0d0f0d2a0e0e0d2a0d2a0e0e0d2a0e0e0d0f0d0e0e0e0e290e2a0d0e0e0e0e290f0d0d0009736e370e0e0d0f0d2a0d0f0d2a0d0f0d2a0d0f0d0e0e2a0d0e0e0e0d2a0e2a0d0e0e0e0d0f0d0f0d0e0e0e0d0f0d0e0e2a0d0e0e2a0d0e0e0e0e0e0d0f0d2a0d0f0d0e0e2a0d0e0e2a0d2a0d0f0d2a0d0f0d0e0e0e0d0f0d2a0d2a0e0e0d0f0d2a0d0f0d000d05000000000000000000000000"
                            },
                            {
                                "name": "Computer",
                                "type": "hdmi",
                                "data": "2600cc006e370e0e0e0e0d2a0e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0e0e2a0d2a0d0f0d0e0e0e0d0f0d0f0d0e0e0e0d0f0d2a0d0f0d2a0d0f0d0e0e0e0e0e0d2a0e2a0d0e0e2a0d0e0e2a0d2a0d0f0d2a0d0f0d0e0e0e0d0f0d2a0d2a0e0e0d0f0d0e0e0e0d0009746d380d0e0e0e0d2a0e0e0d2a0e0e0d2a0e0e0d0f0d2a0d0f0d0f0d2a0d2a0e0e0d0f0d0e0e0e0d0f0d0e0e0e0e0e0d2a0e0e0d2a0e0e0d0f0d0e0e0e0d2a0e2a0d0e0e2a0d0e0e2a0d2a0d0f0d2a0d0f0d0e0e0e0e0e0d2a0e290e0e0e0e0d0f0d0e0e000d05000000000000000000000000"
                            }
                        ]
                    }
                }

**Comment by perote2000** [comment]
Only On/Off and input selection are available under you  TV "Receiver", you can there on/off device and change input... only that... to access to Volume (by pressing physical Iphone vol+ and -) and other options like select, arrowUp, arrowDown , arrowLeft, arrowRight, back, exit, playPause and info are available by taping screen on remote , accesible by swipping down from top right screen

![IMG_1528](https://user-images.githubusercontent.com/30159929/68962004-5a5f7580-07b2-11ea-99b9-610a45d4483b.JPEG)
![IMG_1529](https://user-images.githubusercontent.com/30159929/68962005-5a5f7580-07b2-11ea-9bf2-e14e4aab3606.PNG)


https://drive.google.com/file/d/1CtCnsmy0tHw5OuuBHwzgS3PqmLmb1hjs/view?usp=sharing
https://drive.google.com/file/d/1pdUTdkxqkVDjZk53md9FW6nraEWZxjDj/view?usp=sharing
