### ISSUE TITLE
Broadlink keeps going to 'sleep'

### ISSUE THREAD

**Issue by rogiervdberg** [AlexanderBabel/homebridge-broadlink-rm#58]
My setup is working fine, but after a couple of hours the broadlink keeps going to 'sleep'. The Broadlink does not react to interaction and I have to unplug the device and plug it back in. After that it works again. Homebridge does not give a error when the device is in 'sleep' mode. 

Is there a solution to keep the device from going into standby/sleep mode?

Thanks!

Rogier

**Comment by kiwi-cam** [comment]
What do you see when it goes to "sleep"?

The plug-in will ping the device every five seconds and mark it as 'inactive' if it disconnects from the network.

**Comment by rogiervdberg** [comment]
I can still turn the tv on in the home app, but nothing happens. The console log displays the commands send, but nothing happens.

Thanks!

Rogier

On 1 Dec 2019, at 20:10, Cameron <notifications@github.com> wrote:

﻿

What do you see when it goes to "sleep"?

The plug-in will ping the device every five seconds and mark it as 'inactive' if it disconnects from the network.

**Comment by kiwi-cam** [comment]
Hi @rogiervdberg 

I've made a few changes to better manage when the Broadlink device drops packets - basically utilising the device state when sending codes. This might help with the "sleep" issue you're having.  Could you try installing from git: `npm install -g git+https://github.com/AlexanderBabel/homebridge-broadlink-rm` and see if it helps the issue? This should install fine over the top of your current installation. You should see version 4.0.4 if this has installed OK.

Let me know how it goes. If you don't have any issues I'll get it updated on npm for all to use.

**Comment by rogiervdberg** [comment]
I tried it and it works!

I have also updated to a better usb adaptor to feed the Broadlink, this also helps in my experience.

Thanks!!

Rogier

On 12 Dec 2019, at 20:52, Cameron <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @rogiervdberg<https://github.com/rogiervdberg>

I've made a few changes to better manage when the Broadlink device drops packets - basically utilising the device state when sending codes. This might help with the "sleep" issue you're having. Could you try installing from git: npm install -g git+https://github.com/AlexanderBabel/homebridge-broadlink-rm and see if it helps the issue? This should install fine over the top of your current installation.

Let me know how it goes. If you don't have any issues I'll get it updated on npm for all to use.

**Comment by kiwi-cam** [comment]
Fix is included in v4.0.4. Will be updated in NPM once a bugfix in v4.0.5 has finished being tested.
