### ISSUE TITLE
added two tv but only one remote shows up in control center

### ISSUE THREAD

**Issue by sushenmathur** [AlexanderBabel/homebridge-broadlink-rm#6]
Hi 
I've have a RM pro and RM mini and i've added two tv's in the config, both show up in  homekit devices but only the tv for RM pro shows up in remote, the one added for rm mini does not show. Any suggestions how to fix

![IMG_C1C8A427A8D7-1](https://user-images.githubusercontent.com/21048866/55158477-c7ce7f80-51aa-11e9-8ba8-29a52cf3295b.jpeg)
![IMG_1515D6B14555-1](https://user-images.githubusercontent.com/21048866/55158483-ca30d980-51aa-11e9-8e2a-4430d3f76e3e.jpeg)

**Comment by S474N** [comment]
And your config.json?

**Comment by sushenmathur** [comment]
Here is my Config
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.0.4",
                    "mac": "78:0f:77:00:e2:66",
                    "isRFSupported": true
                },
                {
                    "address": "192.168.0.6",
                    "mac": "78:0f:77:19:f9:39",
                    "isRFSupported": false
                }
            ],
            "accessories": [
                {
                    "name": "Living Room TV",
                    "type": "tv",
                    "host": "192.168.0.4",
                    "allowResend": true,
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        },
                        "remote": {
                            "select": "260050000001279513121213121213121312131212131213123812381238123812381213123812381212133713371213121312131213121312381213121312381238133712371337150005430001284913000d050000000000000000",
                            "arrowUp": "260050000001279413121213121312131213121312131212133712381238123813371213123812371312133712131238123812131213121312381213123713121312123812381337120005450001274a12000d050000000000000000",
                            "arrowDown": "260050000001279413121213121312131213121312131213123812381337123812371312133712381213121312131238121312131238121312371337133712131337123812131238120005450001274a13000d050000000000000000",
                            "arrowLeft": "260050000001279413121312121312131213121312131213123812381237133713371213123813371238131212381213121312131213121213121337131212381337123812381337120005450001274a13000d050000000000000000",
                            "arrowRight": "260050000001279413121213121313121213121312131213123812371337133712381312123813371337121312131238121312131212131312121337123813121238123812381238120005450001274a13000d050000000000000000",
                            "back": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "exit": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "playPause": "260098000001289c111513371337133811141338113a13371139133812381313121311151312133713381238133713391139111413381213133711141313111411151213121410151100055000012b9a131212391238103b13121337113a11391239113a1337131213131312131213371339131213371115131213121312131311391313121313131312131213131015100005510001294a13000d05",
                            "info": "260050000001289413121213131113121312131212131312123812381337133712381312123713371337123812381213123812131213121312131213121312371312123812381337120005450001274b13000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "DTV",
                                "type": "s_video",
                                "data": [
                                    {
                                        "data": "260050000001269312141213111412131213111312131213113912371238123812371213113912381237123812381213113812131114111411141213111311391213113911381238110005420001254b12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269412131213121312131213111311141213123812371238123812371213113714381212123812381213111411131213121312381113121312381238123712381238110005410001264b11000d050000000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "260050000001279512121336123812371312133712371336123813361237131212131213131311371238113812121411131211151212131213361312121313121312111313121312130005980001274914000d050000000000000000"
                            }
                        ]
                    }
                },
                {
                    "name": "Bedroom TV",
                    "type": "tv",
                    "host": "192.168.0.6",
                    "allowResend": true,
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        },
                        "remote": {
                            "select": "260050000001279513121213121213121312131212131213123812381238123812381213123812381212133713371213121312131213121312381213121312381238133712371337150005430001284913000d050000000000000000",
                            "arrowUp": "260050000001279413121213121312131213121312131212133712381238123813371213123812371312133712131238123812131213121312381213123713121312123812381337120005450001274a12000d050000000000000000",
                            "arrowDown": "260050000001279413121213121312131213121312131213123812381337123812371312133712381213121312131238121312131238121312371337133712131337123812131238120005450001274a13000d050000000000000000",
                            "arrowLeft": "260050000001279413121312121312131213121312131213123812381237133713371213123813371238131212381213121312131213121213121337131212381337123812381337120005450001274a13000d050000000000000000",
                            "arrowRight": "260050000001279413121213121313121213121312131213123812371337133712381312123813371337121312131238121312131212131312121337123813121238123812381238120005450001274a13000d050000000000000000",
                            "back": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "exit": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "playPause": "260098000001289c111513371337133811141338113a13371139133812381313121311151312133713381238133713391139111413381213133711141313111411151213121410151100055000012b9a131212391238103b13121337113a11391239113a1337131213131312131213371339131213371115131213121312131311391313121313131312131213131015100005510001294a13000d05",
                            "info": "260050000001289413121213131113121312131212131312123812381337133712381312123713371337123812381213123812131213121312131213121312371312123812381337120005450001274b13000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "DTV",
                                "type": "s_video",
                                "data": [
                                    {
                                        "data": "260050000001269312141213111412131213111312131213113912371238123812371213113912381237123812381213113812131114111411141213111311391213113911381238110005420001254b12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269412131213121312131213111311141213123812371238123812371213113714381212123812381213111411131213121312381113121312381238123712381238110005410001264b11000d050000000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "260050000001279512121336123812371312133712371336123813361237131212131213131311371238113812121411131211151212131213361312121313121312111313121312130005980001274914000d050000000000000000"
                            }
                        ]
                    }
                },
            ]
        }
    ]
}`

**Comment by sushenmathur** [comment]
@S474N here is my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.0.4",
                    "mac": "78:0f:77:00:e2:66",
                    "isRFSupported": true
                },
                {
                    "address": "192.168.0.6",
                    "mac": "78:0f:77:19:f9:39",
                    "isRFSupported": false
                }
            ],
            "accessories": [
                {
                    "name": "Living Room TV",
                    "type": "tv",
                    "host": "192.168.0.4",
                    "allowResend": true,
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        },
                        "remote": {
                            "select": "260050000001279513121213121213121312131212131213123812381238123812381213123812381212133713371213121312131213121312381213121312381238133712371337150005430001284913000d050000000000000000",
                            "arrowUp": "260050000001279413121213121312131213121312131212133712381238123813371213123812371312133712131238123812131213121312381213123713121312123812381337120005450001274a12000d050000000000000000",
                            "arrowDown": "260050000001279413121213121312131213121312131213123812381337123812371312133712381213121312131238121312131238121312371337133712131337123812131238120005450001274a13000d050000000000000000",
                            "arrowLeft": "260050000001279413121312121312131213121312131213123812381237133713371213123813371238131212381213121312131213121213121337131212381337123812381337120005450001274a13000d050000000000000000",
                            "arrowRight": "260050000001279413121213121313121213121312131213123812371337133712381312123813371337121312131238121312131212131312121337123813121238123812381238120005450001274a13000d050000000000000000",
                            "back": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "exit": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "playPause": "260098000001289c111513371337133811141338113a13371139133812381313121311151312133713381238133713391139111413381213133711141313111411151213121410151100055000012b9a131212391238103b13121337113a11391239113a1337131213131312131213371339131213371115131213121312131311391313121313131312131213131015100005510001294a13000d05",
                            "info": "260050000001289413121213131113121312131212131312123812381337133712381312123713371337123812381213123812131213121312131213121312371312123812381337120005450001274b13000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "DTV",
                                "type": "s_video",
                                "data": [
                                    {
                                        "data": "260050000001269312141213111412131213111312131213113912371238123812371213113912381237123812381213113812131114111411141213111311391213113911381238110005420001254b12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269412131213121312131213111311141213123812371238123812371213113714381212123812381213111411131213121312381113121312381238123712381238110005410001264b11000d050000000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "260050000001279512121336123812371312133712371336123813361237131212131213131311371238113812121411131211151212131213361312121313121312111313121312130005980001274914000d050000000000000000"
                            }
                        ]
                    }
                },
                {
                    "name": "Bedroom TV",
                    "type": "tv",
                    "host": "192.168.0.6",
                    "allowResend": true,
                    "data": {
                        "on": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "off": "260050000001269511141114111411141114111411131213113911391139113911391114113812381114111411391139113911141114111312381139111411141114113911391139110005450001264b11000d050000000000000000",
                        "volume": {
                            "up": "260058000001289313121312131213121213121213121312133713371337133713371312133712371337133713121337131213121337131213121312133712131237133713121336140005440001284a13000c560001284913000d05",
                            "down": "260050000001289413121213121213121312131213121312133713371337133712371312133713371337133713371337121213121337131213121312131213121337133712131237130005440001264b13000d050000000000000000"
                        },
                        "remote": {
                            "select": "260050000001279513121213121213121312131212131213123812381238123812381213123812381212133713371213121312131213121312381213121312381238133712371337150005430001284913000d050000000000000000",
                            "arrowUp": "260050000001279413121213121312131213121312131212133712381238123813371213123812371312133712131238123812131213121312381213123713121312123812381337120005450001274a12000d050000000000000000",
                            "arrowDown": "260050000001279413121213121312131213121312131213123812381337123812371312133712381213121312131238121312131238121312371337133712131337123812131238120005450001274a13000d050000000000000000",
                            "arrowLeft": "260050000001279413121312121312131213121312131213123812381237133713371213123813371238131212381213121312131213121213121337131212381337123812381337120005450001274a13000d050000000000000000",
                            "arrowRight": "260050000001279413121213121313121213121312131213123812371337133712381312123813371337121312131238121312131212131312121337123813121238123812381238120005450001274a13000d050000000000000000",
                            "back": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "exit": "260050000001279413121213121312131213121312121312133712381238123812381312123812381411123713121337121312131213121312381213123812131238123812371337130005440001284a13000d050000000000000000",
                            "playPause": "260098000001289c111513371337133811141338113a13371139133812381313121311151312133713381238133713391139111413381213133711141313111411151213121410151100055000012b9a131212391238103b13121337113a11391239113a1337131213131312131213371339131213371115131213121312131311391313121313131312131213131015100005510001294a13000d05",
                            "info": "260050000001289413121213131113121312131212131312123812381337133712381312123713371337123812381213123812131213121312131213121312371312123812381337120005450001274b13000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "DTV",
                                "type": "s_video",
                                "data": [
                                    {
                                        "data": "260050000001269312141213111412131213111312131213113912371238123812371213113912381237123812381213113812131114111411141213111311391213113911381238110005420001254b12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269511131213121312131213121311131213113912381138113912381212123811391114113812131238113813121114111411391213113812131213113912371238120005410001264a12000d050000000000000000",
                                        "pause": 0.7
                                    },
                                    {
                                        "data": "260050000001269412131213121312131213111311141213123812371238123812371213113714381212123812381213111411131213121312381113121312381238123712381238110005410001264b11000d050000000000000000"
                                    }
                                ]
                            },
                            {
                                "name": "AppleTV",
                                "type": "hdmi",
                                "data": "260050000001279512121336123812371312133712371336123813361237131212131213131311371238113812121411131211151212131213361312121313121312111313121312130005980001274914000d050000000000000000"
                            }
                        ]
                    }
                },
            ]
        }
    ]
}

**Comment by mafyata** [comment]
What kind of tv are you using? I tried with my Samsung ue50mu6102 . I can only turn on/off and volume control. When add “remote” section in my config.json , I can’t connect my tv by remote app on my iphone. So I can’t use , up,down,back,input.......

**Comment by S474N** [comment]
Have stupid Philips TV and remote section works perfectly.

**Comment by sushenmathur** [comment]
@S474N the remote section for one of the TV works fine but I cant get the other tv to display in the remote section

**Comment by S474N** [comment]
Sorry, I have only 1 TV with Broadlink.

**Comment by djrams10** [comment]
> Hi
> I've have a RM pro and RM mini and i've added two tv's in the config, both show up in homekit devices but only the tv for RM pro shows up in remote, the one added for rm mini does not show. Any suggestions how to fix
> 
> ![IMG_C1C8A427A8D7-1](https://user-images.githubusercontent.com/21048866/55158477-c7ce7f80-51aa-11e9-8ba8-29a52cf3295b.jpeg)
> ![IMG_1515D6B14555-1](https://user-images.githubusercontent.com/21048866/55158483-ca30d980-51aa-11e9-8e2a-4430d3f76e3e.jpeg)

did you find the solution to display 2 tv on the control center?

**Comment by kiwi-cam** [comment]
No, there haven’t been any updates yet. This issue will be closed when it’s resolved.

**Comment by AlexanderBabel** [comment]
Same as #4
