### ISSUE TITLE
Broadlink RM 3 Red - device type code: "5f36"

### ISSUE THREAD

**Issue by nickv2002** [AlexanderBabel/homebridge-broadlink-rm#63]
I've got this same issue as in the source fork: https://github.com/lprhodes/homebridge-broadlink-rm/issues/515 Essentially a new version of the device that has a different device code:

> [Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.
> 
> Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address "x.x.x.x".
> 

On the linked issue they seemed to conclude it was impossible to add support but, I figured I check here first. Would it be possible to get this device added and working?

**Comment by jgarciah-alt** [comment]
Same problem here... :(
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address...
Any help would be great!

**Comment by nickv2002** [comment]
Looks like this was fixed in the base repo see https://github.com/lprhodes/homebridge-broadlink-rm/issues/515

**Comment by kiwi-cam** [comment]
Luke has been making various updates recently, including to the module that identifies devices. `npm update -g` should resolve this issue as this fork pulls the same module.

**Comment by nickollasaranha** [comment]
@nickv2002 @jgarciah-alt have you managed to get this device to learn IR? I got the same device, and although it is discovered by the plugin, the learn function doesn't work...

**Comment by nickv2002** [comment]
@nickollasaranha I swapped for the Black model before support was added in https://github.com/lprhodes/homebridge-broadlink-rm/issues/515 so I can't tell you 👍 or 👎 sorry.
