### ISSUE TITLE
"enableAutoOff": true,

### ISSUE THREAD

**Issue by djrams10** [AlexanderBabel/homebridge-broadlink-rm#7]
Hello, I set up a swtich tv and I would like to activate the function "enableAutoOff": true I need it to turn off quickly. Could you help me because it worked with the switch but not with tv. I show you my config file. Thanks

>           "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "accessory": "Broadlink RM Learner",
                    "type": "learn-code",
                    "name": "Learn IR",
                    "host": "192.168.86.36"
                },
                {
                    "name": "Television",
                    "type": "tv",
                    "enableAutoOff": true,
                    "onDuration": 1,
                    "data": {
                        "on": "260068001b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000b971b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000d05 "
                    }

>

**Comment by S474N** [comment]
If you have type "tv", why do you want AutoOff? AutoOff is for switch/light/outlet.

**Comment by djrams10** [comment]
because I can turn on my TV with the hdmi cec, which will be a problem because he does not know the state of my tv. I hope you understand me well. Do you think it's possible?

**Comment by S474N** [comment]
And has your TV ETH RJ45/WiFi?

**Comment by djrams10** [comment]
ETH RJ45, why? it's a television of 2013. I use this plugin. https://github.com/gw-wiscon/homebridge-philipstv#readme . I can know the state, put it out, but I can not start it. That's why I need the broadlink plugin, but I would like it to be displayed as a tv.

**Comment by kiwi-cam** [comment]
The reason S474N asks is that this plugin uses pingIPAddress to monitor the TVs status. If you add this to your TV config with the host name or IP of your TV the status will update based on whether it’s on the network.

**Comment by djrams10** [comment]
It would be really great !!! Could you give me an example of config.json to point me in the right direction? thank you in advance

**Comment by djrams10** [comment]
What do you think?

> "name": "Télévision",
                    "type": "switch",
                    "pingIPAddress": "192.168.86.123",
                    "data": {
                        "on": "260068001b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000b971b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000d05 "
                    }

>

**Comment by djrams10** [comment]
It does not work, it turns on and off continuously and it ends up turning off the TV

**Comment by djrams10** [comment]
the pingIPAddress does not work with the "switchtv", it works with the "switch" but it turns on and off, until turn off the tv.

**Comment by kiwi-cam** [comment]
Try adding 
"pingIPAddressStateOnly": true,
too.

**Comment by djrams10** [comment]
thank you, it's done. All works with the switch, but can you confirm me, it does not work with type "TV". I tried and no reaction.

**Comment by S474N** [comment]
Type is "tv", not "TV".

**Comment by djrams10** [comment]
yes, excuse me. should it work for you?

**Comment by djrams10** [comment]
I identified the problem. The pingadress check does not go back to the homekit directly. I am forced to open the home app to update and interop the ip. Could you help me solve this problem? Thank you

**Comment by djrams10** [comment]
after a long search, I ended up reinstalling everything and it works. the status goes back to homekit. Thank you all
