### ISSUE TITLE
TV accessory does not show inputs iOS 13.3.1

### ISSUE THREAD

**Issue by mm07vk** [AlexanderBabel/homebridge-broadlink-rm#74]
Hi everyone,

The TV accessory does not function properly as the inputs are not show and cannot be selected. I can see the input option as an icon inside the Accessories tab of the TV accessory but it is not functional. The on/off button works properly. 
The issue might be related to the recent iOS 13.3.1 update. 
Is anyone else experiencing this issue?

Here is the relevant part of the config.json:

```
 "accessories": [
	            {
	                "name":"Bedroom TV",
	                "type":"tv",
	                "pingIPAddress":"192.168.0.110",
	                "pingFrequency": 5,
	                "pingIPAddressStateOnly": true, 
	                "data": {
	                    "off": "26005...",
	                    "on": "26005...",      
			    "inputs": 
					[{  "name": "Plus TV", 
					    "type": "hdmi", 
					    "data": "26005..." 
					}]
				   }				
	            }
]
```

<img width="227" alt="Screen Shot 2020-02-25 at 13 24 22" src="https://user-images.githubusercontent.com/61457656/75243246-327ca680-57d2-11ea-8c26-6fec15b5cafa.png"> <img width="236" alt="Screen Shot 2020-02-25 at 13 24 10" src="https://user-images.githubusercontent.com/61457656/75243250-34466a00-57d2-11ea-89e4-ca36895b925c.png">

**Comment by CharlesMonneron** [comment]
I have the same problem with the volume controls as well

**Comment by kiwi-cam** [comment]
I'm running 13.3.1 and not having any issues with inputs or volume. Is there anything in the logs?

**Comment by mm07vk** [comment]
Found the solution:
1. Delete all files in accessories and persist folders found in homebridge directory to clean the accessories cashe
2. Run homebridge
3. Re-add homebridge hub to Home app

Now all of the inputs are shown and functional as expected:
<img width="311" alt="Screen Shot 2020-03-02 at 14 28 41" src="https://user-images.githubusercontent.com/61457656/75676576-28efb480-5c92-11ea-9daa-873d7bbbed6c.png">
