### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by djrams10** [AlexanderBabel/homebridge-broadlink-rm#8]
hello, you see an error on this config.json? it works well but the inputs are not displayed and the tv LG is not displayed in the control center. thanks

>             "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "accessory": "Broadlink RM Learner",
                    "type": "learn-code",
                    "name": "Learn IR",
                    "host": "192.168.86.141"
                },
                {
                    "name": "LG",
                    "type": "tv",
                    "host": "192.168.86.141",
                    "data": {
                        "on": "260050000001289214111411143514111312131114111312133614351411143514361336143613361312131114111336141113121311141114351436133614111336143613361336140005220001284814000d050000000000000000",
                        "off": "260050000001289214111411143514111312131114111312133614351411143514361336143613361312131114111336141113121311141114351436133614111336143613361336140005220001284814000d050000000000000000",
                        "remote": {
                            "select": "260058000001279313121311143613121311131213121311143613361312133613361436133613371311141113361411131213111436131213361336131213361436133613121336130005220001284913000c4c0001284913000d05",
                            "arrowUp": "260058000001289214111312133613121312131114111312133613361411133614361336133713361312131114111312131114111336141113371336133614361336133614111336140005220001284913000c4c0001274a13000d05",
                            "arrowDown": "260058000001269411131213113812131114111411131114113812381113123811381138123811381238111312131114111312131138121311141138113911381138123811131238110005240001274a11000c4f0001264a12000d05",
                            "arrowLeft": "260058000001269511131114113812131114111312131114113811391113123811381138123811381138123811381213111411131213111411131213111411381138123811381238110005240001264b11000c4e0001274a13000d05",
                            "arrowRight": "260050000001289212131114113811141114111312131114113811381213113911381138123811381114113811381213121311141113121311381213111411381139113811381238110005240001274a11000d050000000000000000",
                            "back": "260050000001269411141114113813121113131213121311123813361312133613371336133713361114131113121336141113371212131213361436113812131336131213361337130005230001264a14000d050000000000000000",
                            "exit": "260058000001269413121311133711131213131213121311123813361312113813361238133612381138113812131139113813121336131211131213113911131114113812131138120005240001264b11000c4f0001264b11000d05",
                            "info": "260050000001269411141114113811141113121311141113123811381114113812381138113812381138113911131213111411131238111411131114113812381138113812131139110005240001274a11000d050000000000000000"
                        },
                        "volume": {
                            "up": "260050000001299114111312133613121312131114111312133613361411143514361336143613361312133613121312131114111312131114361311143613361436133613361436130005220001294814000d050000000000000000",
                            "down": "260050000001299114111411133614111312131114111411133614361311143613361435143613361436133614111312131114111312131114111312133614361336133614361336140005220001284913000d050000000000000000"
                        },
                        "inputs": [
                            {
                                "name": "AppleTv",
                                "type": "hdmi",
                                "data": "260050000001259411141015103910141114101510141114103910391114103910391139103910391015101411141014113910391039103911381139103910391015101411141015100005220001254b10000d050000000000000000"
                            },
                            {
                                "name": "TV",
                                "type": "hdmi",
                                "data": "260050000001259411141015103910141114101510141114103910391114103910391139103910391015101411141014113910391039103911381139103910391015101411141015100005220001254b10000d050000000000000000"
                            }
                        ]
                    }
                },
                {
                    "name": "Télé",
                    "type": "tv",
                    "host": "192.168.86.36",
                    "pingIPAddress": "192.168.86.123",
                    "pingFrequency": 2,
                    "pingIPAddressStateOnly": true,
                    "data": {
                        "on": "260068001b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000b971b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000d05",
                        "off": "260068001b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000b971b1e1c1e391f1b1f1b1e1c1e1c1e1b1f1b3b1c1e38201b000b961b1f1b1f381f1b1f1b1f1b1f1b1f1b1f1b3b1b1f381f1b000d05",
                        "remote": {
                            "select": "26001800383b391f1b1f1b1f1b1e1c1e1c3b383b1c1e1b1f1b000d05",
                            "arrowUp": "26003000383c381f1b1f1b1f1b1f1b1f1b3b3a1d1b1f1b1f1d000b94393b381f1c1e1c1e1b1f1b1f1b3b38201b1e1c1e1c000d050000000000000000",
                            "arrowDown": "26003400381f1c1e1b1f1b1f1b1f1b1f1b1f1b3b381f1b1f1b3b1c000b79391f1b1f1b1f1b1e1c1e1c1e1c1e1b3b391f1b1f1b3b1b000d0500000000",
                            "arrowLeft": "2600180038201b1e1c1e1c1e1b1f1c1e1b1f1b3b383c383c1b000d05",
                            "arrowRight": "26001600383c381f1b1f1c1e1b1f1b1f1c3a383b1c1e39000d050000",
                            "back": "26003400381f1c1e1b1f1b1f1b1f1b1f1b1f1b3b381f1b3b1d1d1c000b79391f1b1f1b1f1b1e1c1e1c1e1b1f1b3b391f1b3b1b1f1b000d0500000000",
                            "exit": "26003400381f1c1e1b1f1b1f1b1f1b1f1b1f1b3b381f1b3b1d1d1c000b79391f1b1f1b1f1b1e1c1e1c1e1b1f1b3b391f1b3b1b1f1b000d0500000000",
                            "info": "26001800381f1b1f1b1f1b1f1b1f1b1f1b1f1b3b381f1b3b39000d05"
                        },
                        "volume": {
                            "up": "26009000000124951014113910151039103a1039121310381214101510151014111410391312103a1039103a1014111410151015121211141015101411391039133710391139103911000541000124951014113910151039103a1237101510391114101510151014111410391114103a1039103a1014111410151015101411141015101411391039113811391139103911000d050000000000000000",
                            "down": "26009000000126941114103a1014103a10391139101411391015101411141015101411391015103910151039111410151015101411141015103911141039113910391139103911391000054100012594111410391114103a1039103a1014113910151014111410151014113910151039101510391114101510151014111410151039101510391139103812381139113910000d050000000000000000"
                        }
                    }
                },
                {
                    "name": "Barre de Son",
                    "type": "switch",
                    "host": "192.168.86.36",
                    "enableAutoOff": true,
                    "onDuration": 20,
                    "data": {
                        "on": "2600d800000124951015103911141039113910391114103a10141114101510141114103a10141139101510141139103911141015103911141039113811151014113910391114103a10000541000124951015103911141039113911381114103a1014111411141014111411391014113910151014113910391114101510391114103a103910151014113910391114103a10000541000124951015103911141039113910391114103a10141114101510141114113910141139101510141139103911141015103911141039113910151014113910391114103a10000d05 "
                    }
                }
            ]
        },
        {

>

**Comment by kiwi-cam** [comment]
If you’re just needing some assistance, rather than raising an issue, I’d suggest getting in touch with the user community. The subreddit here are usually pretty helpful: https://www.reddit.com/r/homebridge/
