### ISSUE TITLE
Working Original Plugin

### ISSUE THREAD

**Issue by giuse93or** [AlexanderBabel/homebridge-broadlink-rm#9]
Hello, i installed the plugin on December. I can’t find a way to work tv accessory. How can i install this fork?

**Comment by kiwi-cam** [comment]
Make sure you search the closed issues before opening a new one:
https://github.com/AlexanderBabel/homebridge-broadlink-rm/issues/2#issuecomment-470260064

EDIT - Some people have had issues installing over the top of the existing plugin so it's recommended that you remove the original first.

**Comment by AlexanderBabel** [comment]
@kiwi-cam I updated the referenced command. Therefore it should work now.
