### ISSUE TITLE
TV remote arrows + volume behaviors

### ISSUE THREAD

**Issue by manuchis** [AlexanderBabel/homebridge-broadlink-rm#90]
Hi there, I'm trying to get the plugin working for my settings. 
I'm using the "TV" device to control a soundbar. 
When I send the volume signal, it goes full up or full down, there is no way to make it one step at time. 
I've tried the same with the remote control to manage the subwoofer level, and all the time happens the same. It goes until the minimum or the maximum value. 

I then tried to use pause/interval settings but it was worthless.

Any guess?

**Comment by kiwi-cam** [comment]
That's really odd. Does the volume step when using the device volume? Have you confirmed that the HEX code you're sending is the correct one - not some other code to set MAX volume?

Could you post the logs from when you're adjusting the volume? This should show which codes are being sent and how often.

**Comment by manuchis** [comment]
Well, yes! it was definetivelly that. 
I don't know why, if I push the remote for a long period it sends a different signal than a simple step. So I've re learned all over again, and it works perfect now. 
Thanks!
