### ISSUE TITLE
Airco that gets switched on, then left alone

### ISSUE THREAD

**Issue by chrisremie** [AlexanderBabel/homebridge-broadlink-rm#94]
Hi,

thanks for making this!

I guess I'm not completely understanding the air-conditioner concept.
I would like to send the airco something like 'cool to 24', and then leave it alone, meaning, the airco will switch itself on/off according to the temperature it itself is measuring.
Why is homebridge-broadlink-rm constantly requesting the temperature from the airco?

[7/19/2020, 16:48:10] [Broadlink RM] Daikin addTemperatureCallbackToQueue (requested temperature from device, waiting)

I'm sure I'm missing something,
so how can I accomplish this?

I mean, it is working as far as I understand, but the temp requests do not seem necessary.

Thanks,
Chris.

**Comment by chrisremie** [comment]
Somehow, without making any changes it stopped asking for the temperature...

**Comment by chrisremie** [comment]
Actually, it is still doing it:
[7/20/2020, 04:27:37] [Broadlink RM] Daikin addTemperatureCallbackToQueue (requested temperature from device, waiting)
[7/20/2020, 04:27:38] [Broadlink RM] [INFO] Reported temperature (0) is too low, setting to minTemperature (10).

This is in the config file:
 "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "host": "xxx",
            "accessories": [
                {
                    "type": "air-conditioner",
                    "name": "Daikin",
                    "persistState": true,
                    "temperatureUpdateFrequency": 1000,
                    "minTemperature": 10,
                    "maxTemperature": 28,
                    "data": {

**Comment by kiwi-cam** [comment]
Hi @chrisremie 

There are two things you should be aware of:
1. The Air-conditioning accessory requires a temperature source so you need either: 
    1. A Broadlink device that has a thermometer
    2. A file in the file system that holds the current temperature, as defined in [temperatureFilePath](https://lprhodes.github.io/slate/#air-conditioner)
    3. A DS18B20 sensor attached to a raspberry pi, and setup as [w1device](https://github.com/kiwi-cam/homebridge-broadlink-rm#aircon-accessory)
    4. A Pseudo temperature to prevent errors, as defined in [pseudoDeviceTemperature](https://lprhodes.github.io/slate/#air-conditioner)
2. HomeKit will request the temperature at times. The most common cause of frequent requests is just having the Home app open and refreshing.

**Comment by chrisremie** [comment]
Thanks for your reply Cameron @kiwi-cam!

I understand it better now.
So HomeKit is requesting the temperature from the Airco, and homebridge-broadlink-rm-tv is just accommodating this.
And HomeKit nor homebridge-broadlink-rm-tv is taking any automatic action on its own from this temperature.

As per your list of possibilities, I chose to use pseudoDeviceTemperature.

This seems to be working now how I was expecting.

Chris.
